[settings]
experimental = true
disable_hints = ["python_multi"]
idiomatic_version_file_enable_tools = []

[tools]
actionlint = "latest"
stylua = "latest"
"ubi:apify/apify-cli" = { version = "1.2.1", matching = "apify", exe = "apify" }
usage = "latest"
uv = "latest"

[env._.python.venv]
path = ".venv"
create = true
